# Generated by Django 6.1.1 on 2026-10-04 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('period', models.CharField(choices=[('MONTHLY', 'Mensual'), ('ANNUAL', 'Anual')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('duration_days', models.PositiveIntegerField()),
                ('recharge_discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('benefits', models.JSONField(blank=True, default=list, help_text='Lista de textos con los beneficios.')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'price'],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='plan_price_positive'), models.CheckConstraint(condition=models.Q(('duration_days__gt', 0)), name='plan_duration_positive'), models.CheckConstraint(condition=models.Q(('recharge_discount_percent__gte', 0), ('recharge_discount_percent__lt', 100)), name='plan_recharge_discount_range')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de pago'), ('ACTIVE', 'Activa'), ('FAILED', 'Pago fallido')], default='PENDING', max_length=10)),
                ('duration_days', models.PositiveIntegerField()),
                ('recharge_discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to='payments.payment')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='memberships.membershipplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
