# Generated by Django 6.1.1 on 2026-10-05 19:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0002_audit_and_proof'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('BALANCE', 'Saldo'), ('DATA', 'Datos'), ('VOICE', 'Voz'), ('COMBO', 'Combinado datos y voz')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_demo', models.BooleanField(default=False, help_text='Paquete de ejemplo, no un precio real de ETECSA.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'price'],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='recharge_package_price_positive')],
            },
        ),
        migrations.CreateModel(
            name='RechargeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('phone_number', models.CharField(max_length=13)),
                ('price_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent_applied', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('promotion_snapshot', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pendiente de pago'), ('PROCESSING', 'Procesando'), ('SUCCESS', 'Exitosa'), ('FAILED', 'Fallida')], default='PENDING_PAYMENT', max_length=20)),
                ('provider_reference', models.CharField(blank=True, max_length=100)),
                ('provider_message', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recharge_order', to='payments.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recharge_orders', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='recharges.rechargepackage')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='recharges_r_user_id_b93c6c_idx'), models.Index(fields=['status'], name='recharges_r_status_d73026_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('price_base__gt', 0)), name='recharge_order_base_positive'), models.CheckConstraint(condition=models.Q(('amount_total__gt', 0)), name='recharge_order_total_positive'), models.CheckConstraint(condition=models.Q(('amount_total__lte', models.F('price_base'))), name='recharge_order_total_not_above_base'), models.CheckConstraint(condition=models.Q(('discount_percent_applied__gte', 0), ('discount_percent_applied__lt', 100)), name='recharge_order_discount_range')],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='recharges.rechargepackage')),
            ],
            options={
                'ordering': ['-starts_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='promotion_ends_after_start')],
            },
        ),
    ]
