# Generated by Django 6.1.1 on 2026-10-04 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Remittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('amount_sent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'Dólar estadounidense'), ('EUR', 'Euro')], max_length=3)),
                ('base_rate_used', models.DecimalField(decimal_places=6, max_digits=18)),
                ('spread_percent_used', models.DecimalField(decimal_places=2, max_digits=5)),
                ('effective_rate_used', models.DecimalField(decimal_places=4, max_digits=18)),
                ('amount_cup', models.DecimalField(decimal_places=2, max_digits=14)),
                ('is_vip_rate', models.BooleanField(default=False)),
                ('recipient_name', models.CharField(max_length=120)),
                ('recipient_phone', models.CharField(max_length=13)),
                ('recipient_address', models.CharField(blank=True, max_length=255)),
                ('recipient_account', models.CharField(blank=True, max_length=40)),
                ('delivery_method', models.CharField(choices=[('CASH_DELIVERY', 'Entrega de efectivo en Cuba'), ('LOCAL_TRANSFER', 'Transferencia local en Cuba')], max_length=20)),
                ('payment_method', models.CharField(choices=[('STRIPE', 'Stripe'), ('PAYPAL', 'PayPal'), ('WISE', 'Wise'), ('MERCADO_PAGO', 'Mercado Pago'), ('ENZONA', 'EnZona'), ('ZELLE', 'Zelle'), ('CASH', 'Efectivo')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pendiente de pago'), ('PAID', 'Pagado'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], default='PENDING_PAYMENT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='remittance', to='payments.payment')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remittances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['sender', '-created_at'], name='remittances_sender__c4530d_idx'), models.Index(fields=['status'], name='remittances_status_1fda21_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_sent__gt', 0)), name='remittance_amount_positive'), models.CheckConstraint(condition=models.Q(('effective_rate_used__gt', 0)), name='remittance_rate_positive'), models.CheckConstraint(condition=models.Q(('amount_cup__gt', 0)), name='remittance_cup_positive'), models.CheckConstraint(condition=models.Q(models.Q(('delivery_method', 'CASH_DELIVERY'), models.Q(('recipient_address', ''), _negated=True)), models.Q(('delivery_method', 'LOCAL_TRANSFER'), models.Q(('recipient_account', ''), _negated=True)), _connector='OR'), name='remittance_delivery_data_present')],
            },
        ),
    ]
