# Generated by Django 6.1.1 on 2026-10-04 22:28

import apps.remittances.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remittances', '0001_remittance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='remittance',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to=apps.remittances.models.proof_path),
        ),
        migrations.AddField(
            model_name='remittance',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='RemittanceStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('PENDING_PAYMENT', 'Pendiente de pago'), ('PAID', 'Pagado'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], max_length=20)),
                ('to_status', models.CharField(choices=[('PENDING_PAYMENT', 'Pendiente de pago'), ('PAID', 'Pagado'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], max_length=20)),
                ('source', models.CharField(choices=[('CUSTOMER', 'Cliente'), ('PAYMENT', 'Pago'), ('ADMIN', 'Administrador')], max_length=10)),
                ('note', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('remittance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_log', to='remittances.remittance')),
            ],
            options={
                'ordering': ['changed_at', 'id'],
            },
        ),
    ]
