# Generated by Django 6.1.1 on 2026-10-04 20:56

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'Dólar estadounidense'), ('EUR', 'Euro')], max_length=3)),
                ('target_currency', models.CharField(default='CUP', editable=False, max_length=3)),
                ('base_rate', models.DecimalField(decimal_places=6, max_digits=18)),
                ('standard_spread_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('vip_spread_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['currency', '-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_rate', models.DecimalField(decimal_places=6, max_digits=18)),
                ('standard_spread_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vip_spread_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='exchange_rates.exchangerate')),
            ],
            options={
                'verbose_name_plural': 'exchange rate history',
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('currency', 'target_currency'), name='one_active_rate_per_pair'),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.CheckConstraint(condition=models.Q(('base_rate__gt', 0)), name='rate_base_positive'),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.CheckConstraint(condition=models.Q(('standard_spread_percent__gte', 0), ('standard_spread_percent__lt', 100)), name='rate_standard_spread_range'),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.CheckConstraint(condition=models.Q(('vip_spread_percent__gte', 0), ('vip_spread_percent__lt', 100)), name='rate_vip_spread_range'),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.CheckConstraint(condition=models.Q(('vip_spread_percent__lte', models.F('standard_spread_percent'))), name='rate_vip_spread_not_above_standard'),
        ),
    ]
