# Generated by Django 6.1.1 on 2026-10-04 21:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('purpose', models.CharField(choices=[('MEMBERSHIP', 'Membresía'), ('REMITTANCE', 'Remesa'), ('RECHARGE', 'Recarga')], max_length=20)),
                ('target_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('method', models.CharField(choices=[('STRIPE', 'Stripe'), ('PAYPAL', 'PayPal'), ('WISE', 'Wise'), ('MERCADO_PAGO', 'Mercado Pago'), ('ENZONA', 'EnZona'), ('ZELLE', 'Zelle'), ('CASH', 'Efectivo')], max_length=20)),
                ('provider', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SUCCEEDED', 'Pagado'), ('FAILED', 'Fallido')], default='PENDING', max_length=10)),
                ('external_reference', models.CharField(blank=True, max_length=100)),
                ('instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='payments_pa_user_id_7a85fd_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive'), models.UniqueConstraint(condition=models.Q(('external_reference', ''), _negated=True), fields=('provider', 'external_reference'), name='payment_unique_external_reference')],
            },
        ),
    ]
